### ISSUE TITLE
关于添加评论

### ISSUE THREAD

**Issue by jdnjk** [ZengXiaoPi/Simpfun_Wiki#100]
考虑在文档中添加评论不?教程https://emmachan2021.github.io/docs/tech/docusaurus-comment
要不是需要开启GitHub Discussions,不然我直接pr
附上官网https://giscus.app/zh-CN

**Comment by jdnjk** [comment]
#101

**Comment by jdnjk** [comment]
pr已提交

**Comment by ZengXiaoPi** [comment]
#101
