### ISSUE TITLE
关于常见问题的格式更改建议

### ISSUE THREAD

**Issue by Twelve-eight** [ZengXiaoPi/Simpfun_Wiki#30]
我自己创建的meje下的常见问题我会改为文件夹并配置好后commit/pr来
建议所有常见问题文档都设为文件夹，同时每个问题都给单开一个.md
以及，申请迁移所有常见问题到上一级文档（SFE4）并合并为一个文件夹，文件夹内部再用子一级目录分各个游戏，这样那群B找的时候更显眼。

当然，如果能直接放到根目录（/main）更好（
（_因为确实也不是sfe4独有的内容嘛……_

**Comment by Twelve-eight** [comment]
你要是上学去了看不到的话我申请暂时代理（
但是自己看到更好

**Comment by Twelve-eight** [comment]
![image](https://github.com/ZengXiaoPi/Simpfun_Wiki/assets/127649305/6986d200-49da-4d0a-b89e-cbc6b9c73f62)
你看，官文上常见问题就在根目录欸

**Comment by HanXiMC** [comment]
> 

麻烦您帮我暂时代理一下吧 现在上学没太多精力来搞这个文档 我对于GitHub的代码格式也并不了解 纯粹就是想将自己的一些开服经历和一些小白会遇到的问题上传上来方便大家使用的~

**Comment by HanXiMC** [comment]
> 你要是上学去了看不到的话我申请暂时代理（ 但是自己看到更好

我需要做些什么来方便于你代理吗？

**Comment by ZengXiaoPi** [comment]
你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。

**Comment by ZengXiaoPi** [comment]
> > 
> 
> 麻烦您帮我暂时代理一下吧 现在上学没太多精力来搞这个文档 我对于GitHub的代码格式也并不了解 纯粹就是想将自己的一些开服经历和一些小白会遇到的问题上传上来方便大家使用的~

**让你的pr符合主仓库代码是你的义务，而不是我的**

**Comment by ZengXiaoPi** [comment]
你要是改就改吧。

**Comment by Twelve-eight** [comment]
> > 
> 
> 麻烦您帮我暂时代理一下吧 现在上学没太多精力来搞这个文档 我对于GitHub的代码格式也并不了解 纯粹就是想将自己的一些开服经历和一些小白会遇到的问题上传上来方便大家使用的~

其实我更想问你一个问题 哥们你谁来着🤔我没在贡献者里找到。不过main页面里贡献者显示8个，点进去只有7个……你是缺失的那一个？

**Comment by Twelve-eight** [comment]
> 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。

其实现在的布局也有些怪，打开新页面左边确实很清晰2个主文档2个文件夹，但是SFE4的子项特别多，一打开就是一大哈喇……

**Comment by Twelve-eight** [comment]
同时你给SFE4的弄的那一堆子项文档（如何、、、、这种）官文都有，这样第三方文档还写的话定位很尴尬，上不去下不来，卡在这里了

**Comment by Twelve-eight** [comment]
草草草草草我jb昨天好像忘记签到导致我服务器jb被释放了

**Comment by Twelve-eight** [comment]
>
感谢您使用 简幻欢 SFE4.0
服务器已停止。
>


6


>

**Comment by Twelve-eight** [comment]
> 同时你给SFE4的弄的那一堆子项文档（如何、、、、这种）官文都有，这样第三方文档还写的话定位很尴尬，上不去下不来，卡在这里了

但是好像如果消除这一堆文档，怎么放邀请码呢，，，邀请码是在注册文档里面的，删了的话直接没地方了……

哦好像这堆操作确实有用（官文是最基础的操作，三文的偏向实际应用），我回头改改完善一下，也做差异化

**Comment by Twelve-eight** [comment]
另外，我想找一个地方用来记录三文已知需要完善的部分，我自己的可以单开记事本给自己看，但是还是觉得有个统一的待办项目表比较方便，同时也能方便贡献者互相沟通

目前三文格式和文档风格都是作者自定然后有很强的个人色彩（比如很明显我和岚和午夜的文档就能看出来不是一个人写的）这样短期没什么问题 等到规模再扩展一些可能就会因为管理不统一而有弊端（比如各个文档之间的引用啊什么的）了，而且文档的统一性没保证 阅读会因为本身文档就不是一个联通的整体而受到阻碍（你应该知道“三与三十万综合症”吧？
三文是对开服常见问题的总结和对官文做出更精确和具体的补充，所以，我认为的三文的最终形态，应该是立足SFE、涵盖所有常见/高效开服知识的集合。虽然是「简幻欢第三方文档」，但简幻欢始终扮演的只是算力提供者的角色，用户需要的正是开服知识，所以我觉得，我构想的三文理论上没解释错
同时你创立三文之初的想法与此不矛盾。[想到可以像官方文档一样，做一个简幻欢的第三方文档，这样，只要我文档的问题能覆盖大部分的小白的问题，那小白问问题的时候，我就可以直接把文档链接甩给他了。](https://www.yuque.com/zengxiaopi/simpfun/yxwc6w)


关于这个待办项如何汇集和其它意见的讨论，我目前想了俩方案

1是使用你的仓库里的issue，想到了就发issue，正好贴近编辑好管理，缺点就是，你会被GitHub的邮件吵死……
2是找wed给SimpBBS里开一个分区「三文贡献者」，直接在那里面发表，这个我觉得是最佳方案了

关于为什么不使用QQ群，一是QQ群以聊天为主，要它给「创建一堆待办项然后解决」这种办公功能，确实能用，但完全不提倡……二是现在的贡献者在已有的交流群1~10内可以临时交流，但是想系统化管理不能变为主力，交流群又不是单独给贡献者用的；三承接上一条，如果独立建群无异于闭门造车，本身把贡献者集合到一起就是促进交流，但是这样的话就隔绝了来自普通用户的意见；四是QQ不存聊天记录，太弱智了（总结就是不方便管理）。_（还有一点不过可能是我太敏感了 QQ群自带社交属性 冷群了我会尬死 用BBS不更好 就算人全不在了还能看 同时有人想接手更方便）_

我问问wed能不能划一个板块出来吧（感觉不会不行……吧？）不然也没好的办法了。

**Comment by Twelve-eight** [comment]
> 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。

可以参考你的https://determination.top/docs/utgame ，根目录项不多，也一目了然

**Comment by HanXiMC** [comment]
> 
说实话 我不清楚 我只是在简幻欢维基里加入了编辑 因为我有部分Java语言的基础 可以编写一些基础的代码 主要是我并不是专业的人员 也不清楚GitHub 需要时间摸索 但因为学业问题没太多精力 这才会请你帮忙代理

**Comment by HanXiMC** [comment]
> > > 
> > 
> > 
> > 麻烦您帮我暂时代理一下吧 现在上学没太多精力来搞这个文档 我对于GitHub的代码格式也并不了解 纯粹就是想将自己的一些开服经历和一些小白会遇到的问题上传上来方便大家使用的~
> 
> 其实我更想问你一个问题 哥们你谁来着🤔我没在贡献者里找到。不过main页面里贡献者显示8个，点进去只有7个……你是缺失的那一个？

说实话 我不清楚 我只是在简幻欢维基里加入了编辑 因为我有部分Java语言的基础 可以编写一些基础的代码 主要是我并不是专业的人员 也不清楚GitHub 需要时间摸索 但因为学业问题没太多精力 这才会请你帮忙代理

**Comment by HanXiMC** [comment]
> > > 
> > 
> > 
> > 麻烦您帮我暂时代理一下吧 现在上学没太多精力来搞这个文档 我对于GitHub的代码格式也并不了解 纯粹就是想将自己的一些开服经历和一些小白会遇到的问题上传上来方便大家使用的~
> 
> **让你的pr符合主仓库代码是你的义务，而不是我的**

好的 我会尽力抽出时间去适配主仓库代码的

**Comment by Twelve-eight** [comment]
> 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。

准备这么干

**Comment by ZengXiaoPi** [comment]
> > 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。
> 
> 准备这么干

行

**Comment by Twelve-eight** [comment]
> > > 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。
> > 
> > 
> > 准备这么干
> 
> 行

不是你人在这啊
全部复制粘贴出来会直接丢更改好像，对文件做的改动历史都没了，能避免吗还是说没必要

**Comment by ZengXiaoPi** [comment]
> > > > 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。
> > > 
> > > 
> > > 准备这么干
> > 
> > 
> > 行
> 
> 不是你人在这啊 全部复制粘贴出来会直接丢更改好像，对文件做的改动历史都没了，能避免吗还是说没必要

看历史不就完了，直接复制粘贴就行

**Comment by Twelve-eight** [comment]
> > > > > 你要是想干脆就把sfe3删了，sfe4里的整体往外迁移，但是我觉得那样不好看。
> > > > 
> > > > 
> > > > 准备这么干
> > > 
> > > 
> > > 行
> > 
> > 
> > 不是你人在这啊 全部复制粘贴出来会直接丢更改好像，对文件做的改动历史都没了，能避免吗还是说没必要
> 
> 看历史不就完了，直接复制粘贴就行

文件让我给删了哪来历史

**Comment by Twelve-eight** [comment]
不是，找不到文件了就没法对比每个commit的改动了啊

**Comment by Twelve-eight** [comment]
项目库里没删过文件吧，没法直接看这么做的结果
