### ISSUE TITLE
sftp教程安卓部分建议加入APP下载方式

### ISSUE THREAD

**Issue by lzyyyy0101** [ZengXiaoPi/Simpfun_Wiki#8]
[docs/sfe4/30-sftp.md](https://github.com/ZengXiaoPi/Simpfun_Wiki/blob/main/docs/sfe4/30-sftp.md#%E6%B5%81%E7%A8%8Bandroid)
例如3.1文档：[使用SFTP工具进行文件管理#使用手机](https://www.yuque.com/simpfun/sfe/as70aq#pM0wk)
win都有下载链接了，android也想要一个，呜呜呜

**Comment by ZengXiaoPi** [comment]
不给

**Comment by Twelve-eight** [comment]
不给
