### ISSUE TITLE
Apply for project collaborator

### ISSUE THREAD

**Issue by HaHaWTH** [ZengXiaoPi/Simpfun_Wiki#89]
Java developer with 4+ years experience😘
I am currently working on AuthMeReReloaded project and ProjectileKnockback.
btw A Minecraft server software named Polpot is being worked on too:)

List of some projects of mine IIRC🥳: 
https://github.com/HaHaWTH/VillagerProfessionLocker
https://github.com/HaHaWTH/AdvancedSensitiveWords
https://github.com/HaHaWTH/AuthMeReReloaded
https://github.com/HaHaWTH/ClientBoomer
https://www.mcbbs.net/forum.php?mod=viewthread&tid=1483522

Statistics of AuthMeReReloaded:
https://bstats.org/plugin/bukkit/AuthMeReloaded-Fork/18479

I think I have the ability to maintain SFE doc🤔
Hope this application can be approved❤

**Comment by ZengXiaoPi** [comment]
用英文看不懂 关了

**Comment by ZengXiaoPi** [comment]
I cant understand english, use chinese plz

**Comment by ZengXiaoPi** [comment]
哦，明白了，直接提交pr就行。

**Comment by ZengXiaoPi** [comment]
哦，明白了，直接提交pr就行。

**Comment by ZengXiaoPi** [comment]
You can submit an pull request.
let someone become collaborator maybe is a dangerous action.
